# Generated by Django 3.0 on 2019-12-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'user detail', 'verbose_name_plural': 'user details'},
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='confirm_passowrd',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user_name',
        ),
    ]
