# Generated by Django 2.2 on 2020-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ratings',
            field=models.CharField(choices=[('b', 'Bad'), ('a', 'Average'), ('e', 'Excellent')], default='a', max_length=50),
            preserve_default=False,
        ),
    ]
