# Generated by Django 2.2 on 2020-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_student_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=2),
        ),
    ]
