# Generated by Django 2.1 on 2020-01-02 12:26

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20191227_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='name of label')),
                ('user', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='label_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'labels',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='checkbox',
            field=models.BooleanField(default=False, verbose_name='check box'),
        ),
        migrations.AddField(
            model_name='post',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, colors=['#FF0000', '#00FF00', '#0000FF'], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='is_archived'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_copied',
            field=models.BooleanField(default=False, verbose_name='make a copy'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pined',
            field=models.BooleanField(default=False, verbose_name='is pinned'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_trashed',
            field=models.BooleanField(default=False, verbose_name='delete_note'),
        ),
        migrations.AddField(
            model_name='post',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='default.jpg', upload_to='media/note_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='label', to='blog.Label'),
        ),
    ]
