# Generated by Django 2.1 on 2020-01-03 09:34

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200102_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, colors=['#FF0000', '#0f4d92', '#a6dba7', '#00FF00', '#dd82ee', '#8293ee', '#eedd82', '#82eedd'], null=True),
        ),
    ]
